-- Base de datos del microservicio de ventas para mascotas
-- Ejecutar conectado como MASCOTAS_DSY2201

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE ventas CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'DROP TABLE productos CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE productos (
    id NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY (
            START WITH 1
            INCREMENT BY 1
            NOCACHE
        ),

    nombre VARCHAR2(120 CHAR) NOT NULL,
    tipo_animal VARCHAR2(80 CHAR) NOT NULL,
    precio_compra NUMBER(10,2) NOT NULL,
    precio_venta NUMBER(10,2) NOT NULL,
    stock NUMBER(10) NOT NULL,

    CONSTRAINT pk_productos
        PRIMARY KEY (id),

    CONSTRAINT ck_producto_precio_compra
        CHECK (precio_compra > 0),

    CONSTRAINT ck_producto_precio_venta
        CHECK (precio_venta > precio_compra),

    CONSTRAINT ck_producto_stock
        CHECK (stock >= 0)
);

CREATE TABLE ventas (
    id NUMBER(10)
        GENERATED BY DEFAULT AS IDENTITY (
            START WITH 1
            INCREMENT BY 1
            NOCACHE
        ),

    producto_id NUMBER(10) NOT NULL,
    cantidad NUMBER(10) NOT NULL,
    fecha_venta DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_ventas
        PRIMARY KEY (id),

    CONSTRAINT ck_venta_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT fk_venta_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos(id)
);

INSERT INTO productos (
    nombre,
    tipo_animal,
    precio_compra,
    precio_venta,
    stock
)
VALUES (
    'Alimento premium para perros',
    'Perro',
    12000,
    18000,
    20
);

INSERT INTO productos (
    nombre,
    tipo_animal,
    precio_compra,
    precio_venta,
    stock
)
VALUES (
    'Pelota resistente',
    'Perro y gato',
    3500,
    6500,
    30
);

INSERT INTO productos (
    nombre,
    tipo_animal,
    precio_compra,
    precio_venta,
    stock
)
VALUES (
    'Shampoo para mascotas',
    'Perro y gato',
    5000,
    9000,
    15
);

INSERT INTO productos (
    nombre,
    tipo_animal,
    precio_compra,
    precio_venta,
    stock
)
VALUES (
    'Cama mediana para perros',
    'Perro',
    15000,
    26000,
    8
);

INSERT INTO ventas (
    producto_id,
    cantidad,
    fecha_venta
)
VALUES (
    1,
    2,
    DATE '2026-09-20'
);

INSERT INTO ventas (
    producto_id,
    cantidad,
    fecha_venta
)
VALUES (
    2,
    3,
    DATE '2026-09-20'
);

INSERT INTO ventas (
    producto_id,
    cantidad,
    fecha_venta
)
VALUES (
    3,
    2,
    DATE '2026-09-18'
);

INSERT INTO ventas (
    producto_id,
    cantidad,
    fecha_venta
)
VALUES (
    1,
    1,
    DATE '2026-08-15'
);

INSERT INTO ventas (
    producto_id,
    cantidad,
    fecha_venta
)
VALUES (
    4,
    1,
    DATE '2025-12-10'
);

COMMIT;

SELECT *
FROM productos
ORDER BY id;

SELECT *
FROM ventas
ORDER BY id;